#!/usr/bin/env python3
################################################################################
#
#   Filename:           test_valid_anagram.py
#
#   Author:             Arnaud Ongenae
#
################################################################################
from ..valid_anagram import Solution
from .leetcode_test import LeetcodeTest


class _Mixin(object):

    def validate_true(self, string, candidate):
        solution = Solution().isAnagram(string, candidate)
        self.assertTrue(
            solution,
            self._format_error(string, candidate)
        )

    @staticmethod
    def _format_error(string, candidate):
        return (
            'wrong result for the following input:\n'
            '    string:    {!r}\n'
            '    candidate: {!r}\n'
            .format(string, candidate)
        )


class TestValidAnagram(LeetcodeTest, _Mixin):

    def test_1(self):
        self.validate_true('anagram', 'nagaram')
